[character]
success_symbol = "[\\$](bold green)"

[directory]
truncation_length = 6
truncation_symbol = '…/'
truncate_to_repo = true

[hostname]
ssh_only = false
format = '@[$hostname](bold blue) '

[username]
format = '[$user]($style)'
show_always = true

[status]
disabled = false

[aws]
disabled = true

[gcloud]
disabled = true

[battery]
disabled = true

# Wait 10 milliseconds for starship to check files under the current directory.
scan_timeout = 10

# Wait 500 milliseconds for commands to finish when changing into a directory.
command_timeout = 500

